Bookkeeping changes to verify, minor changes to latexdiff

diff --git a/testsuite/verify b/testsuite/verify
--- a/testsuite/verify
+++ b/testsuite/verify
@@ -1,9 +1,11 @@
 #!/bin/csh
-set refversion=1.1.0
+set refversion=1.1.1alpha
 # for comparison with 0.5:
 #set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE  --disable-citation-markup"
 set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE "
 #set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE --math-markup=3"
+
+set reportfile=report.txt
 
 #setenv INTERACTIVE
 alias latexdiff ../latexdiff
@@ -16,7 +18,10 @@ delequ latin9 pollack move-equation nomarkup subscript doubledollar \
 DIFDELCMDBUG eqnarray subscriptm delequ2 schneider gennady umesh underwood endfloat outerrise \
 delequ3 delequ4 "simplefrac --allow-spaces" "master --flatten" titlediffTest2 exampleDiff bornd2 \
 "rolla --math-markup=2" mini "complex-maths --math-markup=1" margalit circonflex mwe-comment "apacite-test --flatten" quoteddollarunderscore units )
+
+#set testroots= ( test subscript )
 # ttest-siunitx ttest-glossaries ttest-chem ttest-cleveref
+
 
 if ( $#argv >= 1 ) then
   if ( $argv[1] == "--reset" ) then
@@ -38,6 +43,11 @@ set failed
 set noexist
 set failedrun
 set pdfout
+if ( ! $?reset ) then 
+  echo "Report of diff test:" > $reportfile
+  latexdiff --version >>& $reportfile
+  echo "--------" >> $reportfile
+endif
 while ( $#testroots >= 1 )
 #foreach test ( $testroots)
   echo $testroots[1]
@@ -49,23 +59,34 @@ while ( $#testroots >= 1 )
     set eopt
   endif
   set sample=$sample[1]
+  printf "%-20s :" $sample[1] >> $reportfile
   echo "========================================="
   echo "Differencing ${sample}-old.tex ${sample}-new.tex (using $eopt)"
-  latexdiff $options $eopt ${sample}-old.tex ${sample}-new.tex > ${sample}-diff.tex
+  ( latexdiff $options $eopt ${sample}-old.tex ${sample}-new.tex > ${sample}-diff.tex) >& ${sample}-latexdiff.log 
 #  diff ${sample}-diff-$refversion.tex ${sample}-diff.tex
+  # sum up the quoted calculation times
+
   if ( $?reset ) then
     \cp  ${sample}-diff.tex  ${sample}-diff-$refversion.tex 
+    \cp ${sample}-latexdiff.log ${sample}-latexdiff-$refversion.log
   else 
     if (! -e ${sample}-diff-$refversion.tex ) then
        echo "Reference version ${sample}-diff-$refversion.tex does not exist."
        set noexist = ( $noexist $sample )
+       echo " noref" >> $reportfile
        goto run
     endif
-    echo "Comparing ${sample}-diff-$refversion.tex and  ${sample}-diff.tex (body only)"
-    sed -n '/begin{document}/,/end{document}/ p' ${sample}-diff-$refversion.tex > tmp-ref.$$.tex
-    sed -n '/begin{document}/,/end{document}/ p' ${sample}-diff.tex > tmp-cur.$$.tex
+    echo "Comparing ${sample}-diff-$refversion.tex and  ${sample}-diff.tex (removing latexdiff date stamp)"
+    # remove 2 lines after pattern
+    sed -e '/%DIF LATEXDIFF DIFFERENCE FILE/,+2d' ${sample}-diff-$refversion.tex > tmp-ref.$$.tex
+    sed -e '/%DIF LATEXDIFF DIFFERENCE FILE/,+2d' ${sample}-diff.tex > tmp-cur.$$.tex
+###    # isolate body
+###    sed -n '/begin{document}/,/end{document}/ p' ${sample}-diff-$refversion.tex > tmp-ref.$$.tex
+###    sed -n '/begin{document}/,/end{document}/ p' ${sample}-diff.tex > tmp-cur.$$.tex
     diff -q tmp-ref.$$.tex tmp-cur.$$.tex
+    \rm tmp-{cur,ref}.$$.tex
     if ( $status ) then
+      echo -n " -fail">> $reportfile
       if (! $run) diff -c ${sample}-diff-$refversion.tex ${sample}-diff.tex
       echo "\07" 
       echo "Comparison of ${sample}-old.tex and ${sample}-new.tex gave different results to reference version. See above for detailed listing."
@@ -74,8 +95,15 @@ while ( $#testroots >= 1 )
       endif
       set failed = ( $failed $sample )
     else
+      echo -n " ok" >> $reportfile 
       echo "Passed comparison..."
     endif
+    # calculate running time from summing reported time
+    set totaltime=`perl -ne 'if (/\(([0-9.]*) s\)/){$sum+=$1; } END {print $sum }' ${sample}-latexdiff.log`
+    set totaltimeref=`perl -ne 'if (/\(([0-9.]*) s\)/){$sum+=$1; } END {print $sum }' ${sample}-latexdiff-$refversion.log`
+    # timediff[1] absolute diff.  timediff[2] % percentage diff rel. to old
+	set timediff=( `echo  $totaltime $totaltimeref | awk  '{ diff=$1-$2; print diff, 100*diff/($2+0.005) }'` )
+    printf " %5.2f s ( %6.2f s)\n" $totaltime $timediff[1]  >> $reportfile
   endif
 run:
   if ( $run ) then 
@@ -89,15 +117,25 @@ run:
     endif
   endif
 end
-if ( ! $?reset && $#failed >= 1 ) then 
+
+
+#if ( ! $?reset && $#failed >= 1 ) then 
+if ( ! $?reset ) then 
+  cat $reportfile
+  unset flagdummy
   foreach fail ( $failed )
+    set flagdummy
     echo kdiff3 ${fail}-diff-$refversion.tex ${fail}-diff.tex
   end
-  echo ""
-  echo "The following test(s) failed:"
-  echo $failed
-  echo "The following test(s) did not have a reference version available:"
-  echo $noexist
+  if ($?flagdummy ) then 
+    echo ""
+    echo "The following test(s) failed:"
+    echo $failed
+  endif
+  if ( "x$noexist" != x ) then
+    echo "The following test(s) did not have a reference version available:"
+    echo $noexist
+  endif
 endif
 
 if ( $run ) then
