LuaLaTeX tests + some dependency package fixes?

diff --git a/testsuite/verify b/testsuite/verify
--- a/testsuite/verify
+++ b/testsuite/verify
@@ -3,13 +3,14 @@ set refversion=1.3.4a
 #set refversion=1.1.0
 # for comparison with 0.5:
 #set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE  --disable-citation-markup"
-set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE "
+# set options="-V -t UNDERLINE -s SAFE -f FLOATSAFE "
+set options="-V -t LUAUNDERLINE -s SAFE -f FLOATSAFE "
 
 # we can set this manually to keep track of modified versions
 #set options="$options --math-markup=FINE"  ; set variant="FINE"
 
 
-if ($?variant) then 
+if ($?variant) then
   set nameext="-$variant"
 else
   set nameext
@@ -48,7 +49,8 @@ if ( $#argv >= 1 ) then
     set dummy="$<"
     set reset
   else if ( $argv[1] == "--run" ) then
-    echo "Running pdflatex on difference files"
+    # echo "Running pdflatex on difference files"
+    echo "Running lualatex on difference files"
     set run=1
   else if ( $argv[1] == "--body-diff" ) then
     echo "Only compare the bodies of .tex files"
@@ -56,7 +58,7 @@ if ( $#argv >= 1 ) then
   else
     unset reset
   endif
-else 
+else
   unset reset
 endif
 
@@ -64,7 +66,7 @@ set failed
 set noexist
 set failedrun
 set pdfout
-if ( ! $?reset ) then 
+if ( ! $?reset ) then
   echo "Report of diff test:" > $reportfile
   latexdiff --version >>& $reportfile
   echo "Options: $options" >> $reportfile
@@ -76,7 +78,7 @@ while ( $#testroots >= 1 )
   echo "$testroots[1]"
   set sample=( $testroots[1] )
   shift testroots
-  if ( $#sample > 1 ) then 
+  if ( $#sample > 1 ) then
     set eopt="$sample[2-]"
   else
     set eopt
@@ -85,21 +87,21 @@ while ( $#testroots >= 1 )
   printf "%-20s :" $sample[1] >> $reportfile
   echo "========================================="
   echo "Differencing ${sample}-old.tex ${sample}-new.tex (using $eopt)"
-  ( latexdiff $options $eopt ${sample}-old.tex ${sample}-new.tex > ${sample}-diff$nameext.tex) >& ${sample}-latexdiff$nameext.log 
+  ( latexdiff $options $eopt ${sample}-old.tex ${sample}-new.tex > ${sample}-diff$nameext.tex) >& ${sample}-latexdiff$nameext.log
 #  diff ${sample}-diff-$refversion.tex ${sample}-diff.tex
   # sum up the quoted calculation times
 
   if ( $?reset ) then
-    \cp  ${sample}-diff$nameext.tex  ${sample}-diff$nameext-$refversion.tex 
+    \cp  ${sample}-diff$nameext.tex  ${sample}-diff$nameext-$refversion.tex
     \cp ${sample}-latexdiff${nameext}.log ${sample}-latexdiff${nameext}-$refversion.log
-  else 
+  else
     if (! -e ${sample}-diff${nameext}-$refversion.tex ) then
        echo "Reference version ${sample}-diff$nameext-$refversion.tex does not exist."
        set noexist = ( $noexist $sample )
        echo " noref" >> $reportfile
        goto run
     endif
-	if ( ! $bodydiff ) then 
+	if ( ! $bodydiff ) then
       echo "Comparing ${sample}-diff-$refversion.tex and  ${sample}-diff.tex (removing latexdiff date stamp)"
       # remove 2 lines after pattern
       sed -e '/%DIF LATEXDIFF DIFFERENCE FILE/,+2d' ${sample}-diff${nameext}-$refversion.tex > tmp-ref.$$.tex
@@ -114,14 +116,14 @@ while ( $#testroots >= 1 )
     if ( $status ) then
       echo -n " fail">> $reportfile
       if (! $run) diff -c ${sample}-diff${nameext}-$refversion.tex ${sample}-diff${nameext}.tex
-      echo "\07" 
+      echo "\07"
       echo "Comparison of ${sample}-old.tex and ${sample}-new.tex gave different results to reference version. See above for detailed listing."
       if ( $?INTERACTIVE ) then
-        echo "Press Return to continue" ; set dummy="$<" 
+        echo "Press Return to continue" ; set dummy="$<"
       endif
       set failed = ( $failed $sample )
     else
-      echo -n " ok" >> $reportfile 
+      echo -n " ok" >> $reportfile
       echo "Passed comparison..."
     endif
     # calculate running time from summing reported time
@@ -133,10 +135,12 @@ while ( $#testroots >= 1 )
     \rm tmp-{cur,ref}.$$.tex
   endif
 run:
-  if ( $run ) then 
-    pdflatex -interaction=batchmode ${sample}-diff${nameext}.tex
+  if ( $run ) then
+    # pdflatex -interaction=batchmode ${sample}-diff${nameext}.tex
+    # lualatex -interaction=batchmode ${sample}-diff${nameext}.tex
+    latexmk -lualatex ${sample}-diff${nameext}.tex
 
-    if ($status || ! -e ${sample}-diff.pdf ) then 
+    if ($status || ! -e ${sample}-diff.pdf ) then
        echo "Compilation of ${sample}-diff${nameext}.tex did not complete as expected."
        set failedrun=($failedrun ${sample}-diff${nameext}.tex)
     else
@@ -146,15 +150,15 @@ run:
 end
 
 
-#if ( ! $?reset && $#failed >= 1 ) then 
-if ( ! $?reset ) then 
+#if ( ! $?reset && $#failed >= 1 ) then
+if ( ! $?reset ) then
   cat $reportfile
   unset flagdummy
   foreach fail ( $failed )
     set flagdummy
     echo kdiff3 ${fail}-diff${nameext}-$refversion.tex ${fail}-diff${nameext}.tex ' &'
   end
-  if ($?flagdummy ) then 
+  if ($?flagdummy ) then
     echo ""
     echo "The following test(s) failed:"
     echo $failed
